# Configuration file for S&P 500 Prediction Project

# Data Configuration
data:
  symbol: "^GSPC"  # S&P 500 symbol
  start_date: "2010-01-01"
  end_date: null  # Will use current date if null
  cache_data: true
  force_download: false

# Technical Indicators
technical_indicators:
  sma_windows: [5, 10, 20, 50, 100, 200]
  ema_windows: [5, 10, 20, 50, 100, 200]
  rsi_window: 14
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  bollinger_window: 20
  bollinger_std: 2
  volatility_windows: [20, 50]
  momentum_periods: [5, 10, 20]

# Target Variables
targets:
  prediction_horizons: [1, 5, 10, 20, 63]  # days
  multi_class_thresholds: [-0.05, 0, 0.05]  # for multi-class targets

# Data Preprocessing
preprocessing:
  missing_values_method: "drop"  # drop, forward_fill, interpolate
  outlier_method: "zscore"  # zscore, iqr
  outlier_threshold: 3.0
  normalization_method: "standard"  # standard, minmax, robust
  remove_outlier_columns: ["Returns", "Volatility_20", "RSI", "MACD"]

# Model Configuration
models:
  linear_regression:
    fit_intercept: true
    normalize: false
  
  random_forest:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
  
  kmeans:
    n_clusters_range: [2, 11]
    random_state: 42
    n_init: 10

# Data Splitting
data_splitting:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  maintain_temporal_order: true

# Cross-Validation
cross_validation:
  method: "TimeSeriesSplit"  # TimeSeriesSplit, KFold
  n_splits: 5
  test_size: 0.2

# Performance Metrics
metrics:
  regression: ["rmse", "mae", "mape", "r2"]
  classification: ["accuracy", "precision", "recall", "f1"]
  clustering: ["inertia", "silhouette_score"]

# Visualization
visualization:
  style: "seaborn-v0_8"
  figure_size: [12, 8]
  dpi: 100
  save_format: "png"
  color_palette: "husl"

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/sp500_prediction.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Output
output:
  data_dir: "data"
  models_dir: "models"
  results_dir: "results"
  plots_dir: "plots"
  reports_dir: "reports"

# Feature Engineering
feature_engineering:
  create_lag_features: true
  lag_periods: [1, 2, 3, 5]
  create_rolling_features: true
  rolling_windows: [5, 10, 20]
  create_interaction_features: true
  interaction_pairs: [["SMA_20", "RSI"], ["MACD", "Volatility_20"]]

# Risk Management
risk_management:
  max_position_size: 0.1  # 10% of portfolio
  stop_loss: 0.05  # 5% stop loss
  take_profit: 0.10  # 10% take profit
  max_drawdown: 0.20  # 20% max drawdown
